// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4mPToOEfOUkQ1A9j2Q-C8aukbc28e8to',
    appId: '1:617396900821:web:25b4f79b8f36b0ff24635c',
    messagingSenderId: '617396900821',
    projectId: 'rochajohn-job-timer',
    authDomain: 'rochajohn-job-timer.firebaseapp.com',
    storageBucket: 'rochajohn-job-timer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_cJkHJDIjSho7LkI2dmv28ppaVlCFuy4',
    appId: '1:617396900821:android:7a4eec55072f177324635c',
    messagingSenderId: '617396900821',
    projectId: 'rochajohn-job-timer',
    storageBucket: 'rochajohn-job-timer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5jG1A_TLpcHVCxJXR31EwtV2JLnt-uk0',
    appId: '1:617396900821:ios:1dfb89321b1c2a3724635c',
    messagingSenderId: '617396900821',
    projectId: 'rochajohn-job-timer',
    storageBucket: 'rochajohn-job-timer.appspot.com',
    iosClientId: '617396900821-poed4p64f009bnepfm671hjpq3jbuioa.apps.googleusercontent.com',
    iosBundleId: 'br.com.rochajohnathan.jobTimer',
  );
}
